// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace test {

static const char* TestService_method_names[] = {
  "/test.TestService/getData",
};

std::unique_ptr< TestService::Stub> TestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestService::Stub> stub(new TestService::Stub(channel));
  return stub;
}

TestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_getData_(TestService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TestService::Stub::getData(::grpc::ClientContext* context, const ::test::Data& request, ::test::MsgReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_getData_, context, request, response);
}

void TestService::Stub::experimental_async::getData(::grpc::ClientContext* context, const ::test::Data* request, ::test::MsgReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, response, std::move(f));
}

void TestService::Stub::experimental_async::getData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test::MsgReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, response, std::move(f));
}

void TestService::Stub::experimental_async::getData(::grpc::ClientContext* context, const ::test::Data* request, ::test::MsgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, response, reactor);
}

void TestService::Stub::experimental_async::getData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test::MsgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_getData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test::MsgReply>* TestService::Stub::AsyncgetDataRaw(::grpc::ClientContext* context, const ::test::Data& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::test::MsgReply>::Create(channel_.get(), cq, rpcmethod_getData_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::test::MsgReply>* TestService::Stub::PrepareAsyncgetDataRaw(::grpc::ClientContext* context, const ::test::Data& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::test::MsgReply>::Create(channel_.get(), cq, rpcmethod_getData_, context, request, false);
}

TestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestService::Service, ::test::Data, ::test::MsgReply>(
          [](TestService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::test::Data* req,
             ::test::MsgReply* resp) {
               return service->getData(ctx, req, resp);
             }, this)));
}

TestService::Service::~Service() {
}

::grpc::Status TestService::Service::getData(::grpc::ServerContext* context, const ::test::Data* request, ::test::MsgReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

